-- ============================================================================
-- DEPRECATED — DO NOT RUN
-- ============================================================================
--
-- This migration has been SUPERSEDED by:
--   fix_user_self_edit_privilege_escalation.sql
--
-- Original purpose: Fix check_profile_updates() to use public.is_admin()
-- instead of role = 'admin', allowing superadmin accounts full access.
--
-- Why deprecated: This file contained an INSECURE version of the function
-- that had ZERO column restrictions for regular users editing their own
-- profile (line 76: IF auth.uid() = NEW.id THEN RETURN NEW).
-- Running this file would silently revert the security fix in
-- fix_user_self_edit_privilege_escalation.sql (AUDIT C1/C3 finding).
--
-- The canonical version with all security restrictions is maintained in:
--   fix_user_self_edit_privilege_escalation.sql
--
-- AUDIT FIX C3: File neutralized on 2026-08-07 to prevent accidental
-- revert of security fixes. This file is now a no-op.
-- ============================================================================

-- No-op: The canonical function is defined in fix_user_self_edit_privilege_escalation.sql
-- DO NOT add any CREATE OR REPLACE FUNCTION statements to this file.
