import json
import uuid
import os
import sys

def main():
    print("==================================================")
    print("   Chuti + Quotes Unified DB Migration Script")
    print("==================================================")

    # File names
    CHUTI_AUTH_FILE = "chuti_auth_users.json"
    QUOTES_AUTH_FILE = "quotes_auth_users.json"
    CHUTI_PROFILES_FILE = "chuti_profiles.json"
    QUOTES_PROFILES_FILE = "quotes_profiles.json"
    QUOTES_RECORDS_FILE = "quotes_records.json"
    QUOTES_TODOS_FILE = "quotes_todos.json"
    QUOTES_COMPLIANCE_RULES_FILE = "quotes_compliance_rules.json"
    QUOTES_LOGIN_CODES_FILE = "quotes_login_codes.json"

    # Check if files exist
    required_files = [
        CHUTI_AUTH_FILE, QUOTES_AUTH_FILE,
        CHUTI_PROFILES_FILE, QUOTES_PROFILES_FILE,
        QUOTES_RECORDS_FILE, QUOTES_TODOS_FILE,
        QUOTES_COMPLIANCE_RULES_FILE, QUOTES_LOGIN_CODES_FILE
    ]

    missing_files = [f for f in required_files if not os.path.exists(f)]
    if missing_files:
        print("\n[ERROR] Missing required JSON export files:")
        for f in missing_files:
            print(f" - {f}")
        print("\nPlease export the tables from Supabase as JSON and place them in this folder.")
        print("To export, run in Supabase SQL editor: ")
        print("  SELECT json_agg(t) FROM auth.users t; (Save as JSON)")
        print("  SELECT json_agg(t) FROM public.profiles t; (Save as JSON)")
        print("  SELECT json_agg(t) FROM public.records t; (Save as JSON)")
        print("  ...")
        sys.exit(1)

    print("\n[1/5] Loading JSON data...")
    with open(CHUTI_AUTH_FILE, "r") as f:
        chuti_auth = json.load(f)
    with open(QUOTES_AUTH_FILE, "r") as f:
        quotes_auth = json.load(f)
    with open(CHUTI_PROFILES_FILE, "r") as f:
        chuti_profiles = json.load(f)
    with open(QUOTES_PROFILES_FILE, "r") as f:
        quotes_profiles = json.load(f)
    with open(QUOTES_RECORDS_FILE, "r") as f:
        quotes_records = json.load(f)
    with open(QUOTES_TODOS_FILE, "r") as f:
        quotes_todos = json.load(f)
    with open(QUOTES_COMPLIANCE_RULES_FILE, "r") as f:
        quotes_rules = json.load(f)
    with open(QUOTES_LOGIN_CODES_FILE, "r") as f:
        quotes_login_codes = json.load(f)

    # If tables are nested inside a single key, handle it
    def parse_rows(data):
        if isinstance(data, dict):
            if "rows" in data:
                return data["rows"]
            return [data]
        return data

    chuti_auth = parse_rows(chuti_auth)
    quotes_auth = parse_rows(quotes_auth)
    chuti_profiles = parse_rows(chuti_profiles)
    quotes_profiles = parse_rows(quotes_profiles)
    quotes_records = parse_rows(quotes_records)
    quotes_todos = parse_rows(quotes_todos)
    quotes_rules = parse_rows(quotes_rules)
    quotes_login_codes = parse_rows(quotes_login_codes)

    print(f"Loaded {len(chuti_auth)} Chuti auth users, {len(quotes_auth)} Quotes auth users.")

    # Create mapping maps
    chuti_users_by_email = {u["email"].lower(): u for u in chuti_auth if u.get("email")}
    chuti_profiles_by_id = {p["id"]: p for p in chuti_profiles}
    quotes_profiles_by_id = {p["id"]: p for p in quotes_profiles}
    quotes_users_by_id = {u["id"]: u for u in quotes_auth}

    user_id_map = {} # Maps old_quotes_id -> new_master_id
    sql_statements = []

    sql_statements.append("-- ==================================================")
    sql_statements.append("-- UNIFIED MIGRATION DATA IMPORT SCRIPT")
    sql_statements.append("-- Generated by Antigravity AI")
    sql_statements.append("-- ==================================================\n")

    print("\n[2/5] Processing users and roles mapping...")
    
    # Track which quotes users are migrated
    new_auth_inserts = []
    profile_updates = []
    profile_inserts = []

    # Identify Quotes-only admin (who is not in Chuti) to make them admin in Chuti
    quotes_admins_emails = []
    for q_profile in quotes_profiles:
        if q_profile.get("role") == "admin":
            q_user = quotes_users_by_id.get(q_profile["id"])
            if q_user and q_user.get("email"):
                quotes_admins_emails.append(q_user["email"].lower())

    for q_user in quotes_auth:
        q_id = q_user["id"]
        q_email = q_user.get("email", "").lower()
        q_profile = quotes_profiles_by_id.get(q_id, {})

        # 1. Match common user by email
        if q_email in chuti_users_by_email:
            master_user = chuti_users_by_email[q_email]
            master_id = master_user["id"]
            user_id_map[q_id] = master_id
            
            # Common user gets both access
            quotes_role = q_profile.get("role", "user")
            allowed_types = q_profile.get("allowed_types", ["Quote", "Requote", "Requote Van", "Requote Bike", "Review", "Review Van", "Review Bike", "Individual Review", "Other Site", 'Van', 'Bike', 'Sale'])
            allowed_types_sql = "ARRAY[" + ", ".join([f"'{t}'" for t in allowed_types]) + "]::TEXT[]"
            
            # Check if this user is a supervisor in Chuti
            master_profile = chuti_profiles_by_id.get(master_id, {})
            chuti_role = master_profile.get("role", "user")
            
            # For Chuti supervisors, they remain supervisor, but quotes_role is admin if they were admin in Quotes
            # Otherwise, keep standard roles
            if chuti_role == "supervisor":
                # As per request, supervisors get Quotes admin privileges, so we set quotes_role to 'admin'
                final_quotes_role = 'admin'
            else:
                final_quotes_role = quotes_role

            update_sql = f"""UPDATE public.profiles SET 
  has_chuti_access = TRUE, 
  has_quotes_access = TRUE,
  quotes_role = '{final_quotes_role}',
  allowed_types = {allowed_types_sql}
WHERE id = '{master_id}';"""
            profile_updates.append(update_sql)
            
        else:
            # 2. Quotes-Only User: Create new user in master auth.users and profiles
            new_id = q_id # Keep old ID to prevent remapping records if we want, or generate a new one.
            # Keeping the old ID is safer and cleaner, we just insert it directly into auth.users!
            user_id_map[q_id] = new_id

            # Parse columns for auth.users insert
            # We copy email, encrypted_password, raw_app_meta_data, raw_user_meta_data, aud, role
            email = q_user["email"]
            enc_password = q_user["encrypted_password"]
            raw_app_metadata = json.dumps(q_user.get("raw_app_meta_data", {"provider": "email", "providers": ["email"]}))
            
            # If they are quotes admin and not in Chuti, we make them admin in both!
            is_quotes_admin = q_profile.get("role") == "admin"
            final_chuti_role = "admin" if is_quotes_admin else "user"
            
            raw_user_metadata = q_user.get("raw_user_meta_data", {})
            raw_user_metadata["role"] = final_chuti_role
            raw_user_metadata_str = json.dumps(raw_user_metadata)
            
            aud = q_user.get("aud", "authenticated")
            user_role = q_user.get("role", "authenticated")

            auth_sql = f"""INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, aud, role) 
VALUES ('{new_id}', '00000000-0000-0000-0000-000000000000', '{email}', '{enc_password}', NOW(), NOW(), NOW(), '{raw_app_metadata}'::jsonb, '{raw_user_metadata_str}'::jsonb, '{aud}', '{user_role}');"""
            new_auth_inserts.append(auth_sql)

            # Profile insert for Quotes-only user
            username = q_profile.get("username", email.split('@')[0].upper())
            full_name = q_profile.get("full_name", "")
            allowed_types = q_profile.get("allowed_types", ["Quote", "Requote", "Requote Van", "Requote Bike", "Review", "Review Van", "Review Bike", "Individual Review", "Other Site", 'Van', 'Bike', 'Sale'])
            allowed_types_sql = "ARRAY[" + ", ".join([f"'{t}'" for t in allowed_types]) + "]::TEXT[]"
            
            # Quotes-only admin gets has_chuti_access = true, others false
            has_chuti_access = "TRUE" if is_quotes_admin else "FALSE"
            has_quotes_access = "TRUE"
            
            # Default sign-in/out times are null for Quotes-only user, quotas default
            profile_sql = f"""INSERT INTO public.profiles (id, username, role, full_name, allowed_types, has_chuti_access, has_quotes_access, quotes_role, is_setup_completed)
VALUES ('{new_id}', '{username}', '{final_chuti_role}', '{full_name}', {allowed_types_sql}, {has_chuti_access}, {has_quotes_access}, '{q_profile.get("role", "user")}', TRUE);"""
            profile_inserts.append(profile_sql)

    # 3. Handle Chuti-Only Users (who didn't get processed)
    chuti_processed_ids = set(user_id_map.values())
    chuti_updates = []
    for c_profile in chuti_profiles:
        c_id = c_profile["id"]
        if c_id not in chuti_processed_ids:
            # Chuti-only user: has_chuti_access = TRUE, has_quotes_access = FALSE
            chuti_update_sql = f"UPDATE public.profiles SET has_chuti_access = TRUE, has_quotes_access = FALSE WHERE id = '{c_id}';"
            chuti_updates.append(chuti_update_sql)

    # Write auth users first
    sql_statements.append("-- 1. Insert New Auth Users (Quotes-Only Users)")
    sql_statements.extend(new_auth_inserts)
    sql_statements.append("\n")

    # Write profile inserts and updates
    sql_statements.append("-- 2. Update Common Users Access Flags")
    sql_statements.extend(profile_updates)
    sql_statements.append("\n")

    sql_statements.append("-- 3. Insert Quotes-Only User Profiles")
    sql_statements.extend(profile_inserts)
    sql_statements.append("\n")

    sql_statements.append("-- 4. Update Chuti-Only Users Access Flags")
    sql_statements.extend(chuti_updates)
    sql_statements.append("\n")

    print(f"Created SQL to merge users: {len(new_auth_inserts)} new users, {len(profile_updates)} common user updates, {len(chuti_updates)} chuti-only updates.")

    # 4. Migrate Quotes Records
    print("\n[3/5] Remapping quotes records...")
    records_inserts = []
    for record in quotes_records:
        old_uid = record["user_id"]
        new_uid = user_id_map.get(old_uid)
        if not new_uid:
            print(f"[WARNING] Record {record.get('id')} has unknown user_id {old_uid}. Skipping.")
            continue
        
        file_name = record["file_name"].replace("'", "''")
        branch_name = record["branch_name"]
        codename = record["codename"]
        file_type = record["file_type"]
        submitted_at = record["submitted_at"]
        created_at = record["created_at"]
        r_id = record.get("id", str(uuid.uuid4()))

        rec_sql = f"""INSERT INTO public.records (id, user_id, file_name, branch_name, codename, file_type, submitted_at, created_at) 
VALUES ('{r_id}', '{new_uid}', '{file_name}', '{branch_name}', '{codename}', '{file_type}', '{submitted_at}', '{created_at}');"""
        records_inserts.append(rec_sql)

    sql_statements.append("-- 5. Insert Remapped Quotes Records")
    sql_statements.extend(records_inserts)
    sql_statements.append("\n")
    print(f"Created SQL for {len(records_inserts)} quotes records.")

    # 5. Migrate Todos
    print("\n[4/5] Remapping todos...")
    todos_inserts = []
    for todo in quotes_todos:
        old_uid = todo["user_id"]
        new_uid = user_id_map.get(old_uid)
        if not new_uid:
            print(f"[WARNING] Todo {todo.get('id')} has unknown user_id {old_uid}. Skipping.")
            continue
        
        task = todo["task"].replace("'", "''")
        status = todo["status"]
        comment = todo["comment"].replace("'", "''") if todo.get("comment") else "NULL"
        if comment != "NULL":
            comment = f"'{comment}'"
        todo_date = todo["todo_date"]
        is_all_time = "TRUE" if todo["is_all_time"] else "FALSE"
        created_at = todo["created_at"]
        t_id = todo.get("id", str(uuid.uuid4()))
        codename = todo["codename"]

        todo_sql = f"""INSERT INTO public.todos (id, user_id, codename, task, status, comment, todo_date, is_all_time, created_at) 
VALUES ('{t_id}', '{new_uid}', '{codename}', '{task}', '{status}', {comment}, '{todo_date}', {is_all_time}, '{created_at}');"""
        todos_inserts.append(todo_sql)

    sql_statements.append("-- 6. Insert Remapped Todos")
    sql_statements.extend(todos_inserts)
    sql_statements.append("\n")
    print(f"Created SQL for {len(todos_inserts)} todos.")

    # 6. Migrate Compliance Rules
    print("\n[5/5] Remapping compliance rules...")
    rules_inserts = []
    for rule in quotes_rules:
        r_id = rule["id"]
        category = rule["category"]
        sub_category = rule["sub_category"]
        company_name = rule["company_name"].replace("'", "''") if rule.get("company_name") else "NULL"
        if company_name != "NULL":
            company_name = f"'{company_name}'"
        
        tags = rule.get("company_tags", [])
        if tags:
            tags_sql = "ARRAY[" + ", ".join([f"'{t}'" for t in tags]) + "]::TEXT[]"
        else:
            tags_sql = "NULL"

        title = rule["title"].replace("'", "''") if rule.get("title") else "NULL"
        if title != "NULL":
            title = f"'{title}'"
            
        content = rule["content"].replace("'", "''")
        extra_info = rule["extra_info"].replace("'", "''") if rule.get("extra_info") else "NULL"
        if extra_info != "NULL":
            extra_info = f"'{extra_info}'"
            
        is_deleted = "TRUE" if rule["is_deleted"] else "FALSE"
        created_at = rule["created_at"]
        updated_at = rule["updated_at"]
        updated_by = rule.get("updated_by")
        if updated_by and updated_by in user_id_map:
            updated_by_sql = f"'{user_id_map[updated_by]}'"
        else:
            updated_by_sql = "NULL"

        rule_sql = f"""INSERT INTO public.compliance_rules (id, category, sub_category, company_name, company_tags, title, content, extra_info, is_deleted, created_at, updated_at, updated_by) 
VALUES ('{r_id}', '{category}', '{sub_category}', {company_name}, {tags_sql}, {title}, '{content}', {extra_info}, {is_deleted}, '{created_at}', '{updated_at}', {updated_by_sql});"""
        rules_inserts.append(rule_sql)

    sql_statements.append("-- 7. Insert Compliance Rules")
    sql_statements.extend(rules_inserts)
    sql_statements.append("\n")
    print(f"Created SQL for {len(rules_inserts)} compliance rules.")

    # 7. Migrate Login Codes (Direct Copy, no user mappings needed)
    print("Remapping login codes...")
    codes_inserts = []
    for code_row in quotes_login_codes:
        login_id = code_row["login_id"]
        code = code_row["code"]
        name = code_row["name"].replace("'", "''") if code_row.get("name") else "NULL"
        if name != "NULL":
            name = f"'{name}'"
        updated_at = code_row["updated_at"]

        code_sql = f"""INSERT INTO public.login_codes (login_id, code, name, updated_at) 
VALUES ('{login_id}', '{code}', {name}, '{updated_at}') ON CONFLICT (login_id) DO NOTHING;"""
        codes_inserts.append(code_sql)

    sql_statements.append("-- 8. Insert Login Codes")
    sql_statements.extend(codes_inserts)
    sql_statements.append("\n")
    print(f"Created SQL for {len(codes_inserts)} login codes.")

    # Write output to SQL file
    OUTPUT_FILE = "migration_output.sql"
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(sql_statements))

    print("==================================================")
    print(f"[SUCCESS] Unified migration script written to: {OUTPUT_FILE}")
    print("Run this SQL script in your NEW Supabase project's SQL Editor.")
    print("==================================================")

if __name__ == "__main__":
    main()
